<#
.SYNOPSIS
    Build knFileCatcher (driver + single WPF UX EXE) and pack it as
    one flat folder + zip under <repo>\release.

.DESCRIPTION
    The user-facing surface is now a single executable - knFcUxWpf.exe -
    which directly owns the driver lifetime, holds the FilterPort, drains
    backup requests, and renders the UI. The legacy native EXEs
    (knFcSvc / knFcCli / knFcUx) are NOT built here.

    Pipeline:
      1. Driver         - tools\build-driver.ps1 (cl /kernel /std:c++20 + link /DRIVER)
      2. knFcUxWpf      - dotnet publish -c Release -r win-x64
      3. Flatten into   release\knFileCatcher-<version>\
      4. Compress-Archive -> release\knFileCatcher-<version>.zip

.PARAMETER OutDir
    Where the final folder + zip land. Default: <repo>\release

.PARAMETER Version
    String embedded in the folder/zip name.
    Default: yyyyMMdd-HHmm timestamp.

.PARAMETER NoSign
    Skip the driver signing step.

.EXAMPLE
    .\build-release.ps1
    .\build-release.ps1 -Version 1.0.0
#>

[CmdletBinding()]
param(
    [string] $OutDir,
    [string] $Version,
    [switch] $NoSign,
    # When set, this is a real release: the build consumes version.txt
    # AS-IS and bumps the patch in version.txt for next time. Without
    # this flag the script just rebuilds at the current version.txt value
    # so day-to-day development doesn't burn version numbers.
    [switch] $Release
)

$ErrorActionPreference = "Stop"

$here     = Split-Path -Parent $PSCommandPath
$srcDir   = Split-Path -Parent $here
$repoRoot = Split-Path -Parent $srcDir

if (-not $OutDir)  { $OutDir  = Join-Path $repoRoot 'release' }

# --- version selection --------------------------------------------------
# version.txt holds the version that the NEXT real release will use
# (initial value: 0.1.0).
#   build-release.ps1            -> build at version.txt value, do not bump
#   build-release.ps1 -Release   -> build at version.txt value, then bump
#                                   patch in version.txt after success
#   build-release.ps1 -Version v -> build at v, do not bump (diag/hotfix)
$versionFile = Join-Path $here 'version.txt'
$bumpAfter   = $false
if (-not $Version)
{
    $base = '0.1.0'
    if (Test-Path $versionFile)
    {
        $raw = Get-Content $versionFile -Raw
        if ([string]::IsNullOrWhiteSpace($raw))
        {
            Write-Warning "version.txt is empty - falling back to $base"
        }
        else
        {
            $base = $raw.Trim()
        }
    }
    $vparts = $base -split '\.'
    if ($vparts.Count -ne 3)
    {
        throw "version.txt malformed: '$base' (expected exactly major.minor.patch)"
    }
    foreach ($p in $vparts)
    {
        $tmp = 0
        if (-not [int]::TryParse($p, [ref]$tmp) -or $tmp -lt 0)
        {
            throw "version.txt malformed: '$base' (non-integer or negative component '$p')"
        }
    }
    $Version   = $base
    $bumpAfter = $Release.IsPresent
}

# Build a numeric M.N.P.B used by the driver's RC file. The csproj also
# accepts plain M.N.P via /p:Version=... so the same value works there.
$parts = $Version -split '[-\.]'
function _ToInt($s)
{
    $n = 0
    if ([int]::TryParse($s, [ref]$n)) { return $n } else { return 0 }
}
$verMajor = _ToInt $parts[0]
$verMinor = if ($parts.Count -gt 1) { _ToInt $parts[1] } else { 0 }
$verPatch = if ($parts.Count -gt 2) { _ToInt $parts[2] } else { 0 }
$verBuild = if ($parts.Count -gt 3) { _ToInt $parts[3] } else { 0 }
$verNumeric = "$verMajor.$verMinor.$verPatch"

$driverDir = Join-Path $srcDir 'knFcFlt'
$wpfDir    = Join-Path $srcDir 'knFcUxWpf'

# Regenerate knFcVersion.h before the driver build so the RC compiler
# picks the right numbers. This is what stamps CompanyName=kernullist
# and the version triplet into knFcFlt.sys.
$verHeader = Join-Path $driverDir 'knFcVersion.h'
$verLines  = @(
    '/*',
    ' * knFcVersion.h',
    ' * Auto-generated by build-release.ps1 - do not edit by hand.',
    ' */',
    '#pragma once',
    '',
    "#define KNFC_VER_MAJOR $verMajor",
    "#define KNFC_VER_MINOR $verMinor",
    "#define KNFC_VER_PATCH $verPatch",
    "#define KNFC_VER_BUILD $verBuild",
    "#define KNFC_VER_STR   `"$verMajor.$verMinor.$verPatch.$verBuild`""
)
Set-Content -Path $verHeader -Value $verLines -Encoding ASCII

$folderName = "knFileCatcher-$Version"
$pkgDir     = Join-Path $OutDir $folderName
$workDir    = Join-Path $repoRoot 'build\work'

Write-Host "knFileCatcher release build  version=$Version"
Write-Host "  src     = $srcDir"
Write-Host "  package = $pkgDir"

if (-not (Get-Command dotnet -ErrorAction SilentlyContinue))
{
    throw ".NET SDK not found on PATH - install .NET 8 SDK first."
}

if (Test-Path $pkgDir)  { Remove-Item -Recurse -Force $pkgDir }
if (Test-Path $workDir) { Remove-Item -Recurse -Force $workDir }
New-Item -ItemType Directory -Force -Path $pkgDir  | Out-Null
New-Item -ItemType Directory -Force -Path $workDir | Out-Null

# --- 1) driver ----------------------------------------------------------
Write-Host "`n=== Building driver ==="
$driverWork = Join-Path $workDir 'driver'
$buildDrv   = Join-Path $here 'build-driver.ps1'
if ($NoSign) { & $buildDrv -OutDir $driverWork -NoSign }
else         { & $buildDrv -OutDir $driverWork }
if ($LASTEXITCODE -ne 0)
{
    throw "driver build failed (exit $LASTEXITCODE)"
}
# build-driver.ps1 may throw with $ErrorActionPreference=Stop which does
# not propagate $LASTEXITCODE up; verify the artifact exists too.
$drvSys = Join-Path $driverWork 'knFcFlt.sys'
if (-not (Test-Path -LiteralPath $drvSys))
{
    throw "driver build produced no knFcFlt.sys at $drvSys"
}

Copy-Item -LiteralPath $drvSys -Destination (Join-Path $pkgDir 'knFcFlt.sys')
$drvPdb = Join-Path $driverWork 'knFcFlt.pdb'
if (Test-Path $drvPdb)
{
    Copy-Item $drvPdb (Join-Path $pkgDir 'knFcFlt.pdb')
}

# --- 2) WPF UX ----------------------------------------------------------
# RuntimeIdentifier / SelfContained / PublishSingleFile / DebugType=embedded
# are all set in knFcUxWpf.csproj. dotnet publish picks them up directly.
Write-Host "`n=== Building WPF UX (dotnet publish, single-file self-contained) ==="
$wpfWork = Join-Path $workDir 'wpf'
& dotnet publish (Join-Path $wpfDir 'knFcUxWpf.csproj') `
    -c Release -o $wpfWork --nologo `
    /p:Version=$verNumeric `
    /p:FileVersion="$verMajor.$verMinor.$verPatch.$verBuild" `
    /p:AssemblyVersion="$verMajor.$verMinor.$verPatch.$verBuild" `
    /p:InformationalVersion=$Version
if ($LASTEXITCODE -ne 0)
{
    throw "dotnet publish failed (exit $LASTEXITCODE)"
}
# Single-file publish drops just knFcUxWpf.exe (PDB embedded). Bring it over.
Copy-Item "$wpfWork\knFcUxWpf.exe" (Join-Path $pkgDir 'knFcUxWpf.exe')

# --- zip ---------------------------------------------------------------
$pkgList = Get-ChildItem $pkgDir | ForEach-Object Name | Sort-Object
Write-Host "`n=== Zipping ==="
New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
$zipPath = Join-Path $OutDir "$folderName.zip"
if (Test-Path $zipPath) { Remove-Item $zipPath -Force }
Compress-Archive -Path $pkgDir -DestinationPath $zipPath -CompressionLevel Optimal

Remove-Item -Recurse -Force $workDir -ErrorAction SilentlyContinue

$z = Get-Item $zipPath

# Bump version.txt to the NEXT release's value, but only when this was
# a real -Release build and the whole pipeline above succeeded.
$nextVersionWritten = $null
if ($bumpAfter)
{
    $nextPatch   = $verPatch + 1
    $nextVersion = "$verMajor.$verMinor.$nextPatch"
    Set-Content -Path $versionFile -Value $nextVersion -Encoding ASCII
    $nextVersionWritten = $nextVersion
}

Write-Host ""
Write-Host "knFileCatcher release built:"
Write-Host ("  version : {0}" -f $Version)
Write-Host ("  package : {0}  ({1} files)" -f $pkgDir, $pkgList.Count)
Write-Host ("  zip     : {0}  ({1:N0} bytes)" -f $z.FullName, $z.Length)
if ($nextVersionWritten)
{
    Write-Host ("  bumped  : version.txt -> {0}" -f $nextVersionWritten)
}
else
{
    Write-Host "  bumped  : (no - rerun with -Release to advance version.txt)"
}
